#!/bin/bash
#SBATCH --job-name="install"
#SBATCH --nodes=1
#SBATCH --exclusive
#SBATCH --partition=sm
#SBATCH --time=06:00:00

# on vermilion:
#     Need to load gcc
#     There is no python.  /home/tkaiser2/bin/python is linked to python3

ml gnu9 2>/dev/null || echo gnu9 not loaded
export PATH=/home/tkaiser2/bin:$PATH
which python
which gcc

#Clean out old versions
:<<++++
rm -rf ~/.spack
rm -rf ~/level0*
rm -rf /nopt/nrel/apps/level*
rm -rf /nopt/nrel/apps/modules
rm -rf /nopt/nrel/apps/anaconda/mini_py39_4.9.2
rm -rf ~/install
++++

# tymer, our wall clock timer is in spackit
export PATH=~/spackit:$PATH

setperm() {
echo setting permissions for $1
find $1 -perm -u=x -exec chmod go+x {} \;
find $1 -perm -u=r -exec chmod go+r {} \;
}

tstamp() {
  date +"%y%m%d%H%M"
}

spackit00() {
	source ~/level00/spack/share/spack/setup-env.sh
}
spackit01() {
	source ~/level01/spack/share/spack/setup-env.sh
}
spackit02() {
	source ~/level02/spack/share/spack/setup-env.sh
}

tymer ~/install.$SLURM_JOB_ID start
for l in level00 level01 level02 ; do
  mkdir $l
  cd $l
  git clone https://github.com/spack/spack.git
  cp ~/spackit/swift/$l/spack/etc/spack/defaults/*  spack/etc/spack/defaults
  cd ..
done
  

tymer ~/install.$SLURM_JOB_ID spack installed

spackit00

spack compiler find

spack install gcc@9.4.0

tymer ~/install.$SLURM_JOB_ID gcc installed #1

# need to update compilers.yaml so it points to our install of gnu
export OLDC=`gcc -v 2>&1 | tail -1 | awk '{print $3}'`
export OLDOS=`grep  operating_system: ~/.spack/linux/compilers.yaml | awk '{print $2}'`

cat << BONK > /home/tkaiser2/.spack/linux/compilers.yaml
compilers:
- compiler:
    spec: gcc@9.4.0
    paths:
      cc: /nopt/nrel/apps/level00/gcc-$OLDC/gcc-9.4.0/bin/gcc
      cxx: /nopt/nrel/apps/level00/gcc-$OLDC/gcc-9.4.0/bin/g++
      f77: /nopt/nrel/apps/level00/gcc-$OLDC/gcc-9.4.0/bin/gfortran
      fc: /nopt/nrel/apps/level00/gcc-$OLDC/gcc-9.4.0/bin/gfortran
    flags: {}
    operating_system: $OLDOS
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
BONK

tymer ~/install.$SLURM_JOB_ID compilers.yaml updated #1

spack install gcc@9.4.0
tymer ~/install.$SLURM_JOB_ID gcc installed #2

# need to update compilers.yaml so it points to our second install of gnu


cat << BONK > /home/tkaiser2/.spack/linux/compilers.yaml
compilers:
- compiler:
    spec: gcc@9.4.0
    paths:
      cc: /nopt/nrel/apps/level00/gcc-9.4.0/gcc-9.4.0/bin/gcc
      cxx: /nopt/nrel/apps/level00/gcc-9.4.0/gcc-9.4.0/bin/g++
      f77: /nopt/nrel/apps/level00/gcc-9.4.0/gcc-9.4.0/bin/gfortran
      fc: /nopt/nrel/apps/level00/gcc-9.4.0/gcc-9.4.0/bin/gfortran
    flags: {}
    operating_system: $OLDOS
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
BONK

tymer ~/install.$SLURM_JOB_ID gcc compilers.yaml updated #2

spack install lmod

tymer ~/install.$SLURM_JOB_ID lmod installed

################



spack install cmake
tymer ~/install.$SLURM_JOB_ID cmake installed

spack install cuda
tymer ~/install.$SLURM_JOB_ID cuda installed

spack install  llvm
tymer ~/install.$SLURM_JOB_ID llvm installed

spack install python@3.9.6
tymer ~/install.$SLURM_JOB_ID python@3.9.6 installed

spack install r
tymer ~/install.$SLURM_JOB_ID r installed

spack install julia
tymer ~/install.$SLURM_JOB_ID julia installed

spack install intel-oneapi-compilers
tymer ~/install.$SLURM_JOB_ID intel-oneapi-compilers

spackit01
tymer ~/install.$SLURM_JOB_ID going to level01

spack install intel-oneapi-mpi intel-oneapi-ccl  intel-oneapi-dal intel-oneapi-dnn intel-oneapi-ipp intel-oneapi-ippcp intel-oneapi-mkl intel-oneapi-tbb intel-oneapi-vpl
tymer ~/install.$SLURM_JOB_ID intel-oneapi-tools installed

spack install mpich
tymer ~/install.$SLURM_JOB_ID mpich installed

spack install openmpi
tymer ~/install.$SLURM_JOB_ID openmpi installed

################



#pip for python@3.9.6
cd ~
cd /nopt/nrel/apps/level00/gcc-9.4.0/python-3.9.6/bin
export OPATH=$PATH
export PATH=`pwd`:$PATH
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python get-pip.py
export PATH=$OPATH
cd ~


#python-3.8.11 is installed by R
#pip for python@3.9.6
cd /nopt/nrel/apps/level00/gcc-9.4.0/python-3.8.11/bin
export OPATH=$PATH
export PATH=`pwd`:$PATH
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python get-pip.py
export PATH=$OPATH
cd ~

tymer ~/install.$SLURM_JOB_ID going to level02
spackit02

cd ~
if [ -f vasp.6.1.1.tgz ]; then
spack install --no-check-signature  --no-checksum vasp
tymer ~/install.$SLURM_JOB_ID vasp installed
fi

spack install octave
tymer ~/install.$SLURM_JOB_ID octave installed


################

rm -rf /nopt/nrel/apps/anaconda/mini_py39_4.9.2
wget https://repo.anaconda.com/miniconda/Miniconda3-py39_4.9.2-Linux-x86_64.sh
chmod 755 Miniconda3-py39_4.9.2-Linux-x86_64.sh
./Miniconda3-py39_4.9.2-Linux-x86_64.sh -b -p /nopt/nrel/apps/anaconda/mini_py39_4.9.2 -s
mkdir -p /nopt/nrel/apps/modules/conda
cp spackit/modules/conda/4.9.2.lua /nopt/nrel/apps/modules/conda
chmod 555 /nopt/nrel/apps/anaconda

################

tymer ~/install.$SLURM_JOB_ID conda installed

export NOW=`tstamp`
export VERSION=`ls /nopt/nrel/apps/level00/modules/lmod`
cat << BONK > /nopt/nrel/apps/myenv.$NOW
source /nopt/nrel/apps/level00/gcc-9.4.0/lmod-8.5.6/lmod/8.5.6/init/bash

module use /nopt/nrel/apps/level00/modules/lmod/$VERSION/gcc/9.4.0                                                                
module use /nopt/nrel/apps/level01/modules/lmod/$VERSION/Core                                                                   
module use /nopt/nrel/apps/level02/modules/lmod/$VERSION/Core                                                                   
module use /nopt/nrel/apps/level02/modules/lmod/$VERSION/openmpi/*/*
    
module use /nopt/nrel/apps/modules

alias ma="module avail"

#alias spackit00="source ~/level00/spack/share/spack/setup-env.sh"
#alias spackit01="source ~/level01/spack/share/spack/setup-env.sh"
#alias spackit02="source ~/level02/spack/share/spack/setup-env.sh"
BONK

tymer ~/install.$SLURM_JOB_ID wrote /nopt/nrel/apps/myenv.$NOW

setperm /nopt/nrel/apps

tymer ~/install.$SLURM_JOB_ID  DONE


